replicaCount: 2

image:
  repository: registry.access.redhat.com/ubi9/httpd-24
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

labels:
  app.kubernetes.io/part-of: acme-payment-services
  lightwell.redhat.com/scanned: "true"
  lightwell.redhat.com/risk-class: "HIGH"
