{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "wire-transfer-service.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  wildcardPolicy: None
{{- end }}
