apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "benefits-mgmt-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    {{- include "benefits-mgmt-app.selectorLabels" . | nindent 4 }}
